### PR TITLE
Use constraints.txt in fontc repo

### PR DESCRIPTION
**Pull request by cmyr**
We can actually just use the constraints.txt instead of requirements; this means CI will possibly fail if constraints hasn't been updated after some necessary python package is added, but I think that's okay?

### CODE REVIEW

**Comment by anthrotype** [comment]
if you are no longer using constraints.txt with the -c option, but as a full -r requirements.txt file, how about you actually rename it "requirements.txt" to avoid any confusions?
And maybe the one that only contains higher-level dependencies can be named `requirements.in` following the convention from pip-tools' pip-compile tool: 
https://github.com/jazzband/pip-tools?tab=readme-ov-file#requirements-from-requirementsin

And even better you can actually use pip-compile to create requirements.txt from requirements.in and do away with venv and pip freeze...

**Comment by anthrotype** [comment]
> CI will possibly fail if constraints hasn't been updated after some necessary python package is added, but I think that's okay?

that's unlikely or impossible because for some new necessary python package to be added, one of the packages that are currently pinned in constraints.txt would have to be updated, which constraints.txt should prevent

**Comment by anthrotype** [comment]
> unlikely or impossible

well, unless something completely new gets added to the current fontc/resources/scripts/requirements.txt without regenerating the constraints.txt..

**Comment by cmyr** [comment]
okay sounds good, I've opened https://github.com/googlefonts/fontc/pull/1090 to move to using pip-compile, and then I'll update this when that lands.

**Pull request closed without merging**
